#!/usr/bin/env python3
"""
SkySail gallery builder
-----------------------
Drop photos into the  gallery/  folder, then run:

    python build_gallery.py            # rebuild once
    python build_gallery.py --watch    # keep running: new photos are added automatically

What it does: reads every photo in gallery/, shrinks it for the web (WebP, max 1400 px),
and writes it into index.html as the Gallery page. Nothing else in the page is touched.

Naming (optional):  "07 - Sunrise over the farms, Bengaluru.jpg"
  - the number sets the order (photos are sorted by file name)
  - the text after the dash becomes the caption and the alt text
  - photos with camera-style names (IMG_1234.jpg, WhatsApp Image ..., Untitled.jpg) get a default caption

Needs:  pip install pillow   (add pillow-heif to also accept iPhone .heic photos)
"""
import argparse, base64, hashlib, io, re, sys, time
from pathlib import Path
try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is missing. Install it with:  pip install pillow")

EXTS = {".jpg", ".jpeg", ".png", ".webp"}
try:                                   # iPhone photos (.heic) work if pillow-heif is installed
    from pillow_heif import register_heif_opener
    register_heif_opener()
    EXTS |= {".heic", ".heif"}
except ImportError:
    pass
BLOCK = re.compile(r"/\* GALLERY:AUTO-START.*?\*/.*?/\* GALLERY:AUTO-END \*/", re.S)
GENERIC = re.compile(r"^(img|dsc|pxl|mvimg|screenshot|whatsapp|untitled|photo|image|thumbnail)", re.I)
DEFAULT_CAPTION = "SkySail flight photo"


def natural_key(p: Path):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", p.name.lower())]


def caption_for(p: Path) -> str:
    stem = re.sub(r"^\s*\d+\s*[-_.)]*\s*", "", p.stem).replace("_", " ")
    stem = re.sub(r"\s+", " ", stem).strip(" -")
    if not stem or GENERIC.match(stem):
        return DEFAULT_CAPTION
    return stem


def to_data_uri(p: Path, max_side: int, quality: int, cache: Path) -> str:
    raw = p.read_bytes()
    key = hashlib.sha1(raw + f"{max_side}:{quality}".encode()).hexdigest()
    hit = cache / f"{key}.webp"
    if hit.exists():
        data = hit.read_bytes()
    else:
        im = ImageOps.exif_transpose(Image.open(io.BytesIO(raw)))
        if im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGB")
        im.thumbnail((max_side, max_side), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, "WEBP", quality=quality, method=4)
        data = buf.getvalue()
        cache.mkdir(exist_ok=True)
        hit.write_bytes(data)
    return "data:image/webp;base64," + base64.b64encode(data).decode()


def js_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("<", "\\u003c") + '"'


def build(html: Path, folder: Path, max_side: int, quality: int) -> int:
    if not html.exists():
        sys.exit(f"Can't find {html}")
    text = html.read_text(encoding="utf-8")
    if not BLOCK.search(text):
        sys.exit("The GALLERY:AUTO-START / GALLERY:AUTO-END markers are missing from the HTML.")
    photos = sorted((p for p in folder.iterdir() if p.suffix.lower() in EXTS and not p.name.startswith(".")),
                    key=natural_key)
    if not photos:
        print("  ! the gallery folder is empty, so the page was left unchanged.")
        return -1
    rows = []
    for p in photos:
        try:
            rows.append(f"  {{ src:{js_str(to_data_uri(p, max_side, quality, folder.parent / '.gallery_cache'))}, "
                        f"caption:{js_str(caption_for(p))} }}")
        except Exception as e:  # unreadable or not really an image
            print(f"  ! skipped {p.name}: {e}")
    block = ("/* GALLERY:AUTO-START (generated by build_gallery.py, do not edit by hand) */\n"
             "const GALLERY = [\n" + ",\n".join(rows) + "\n];\n/* GALLERY:AUTO-END */")
    new = BLOCK.sub(lambda m: block, text, count=1)
    if new != text:
        tmp = html.with_suffix(".tmp")
        tmp.write_text(new, encoding="utf-8")
        tmp.replace(html)
    return len(rows)


def signature(folder: Path):
    return tuple(sorted((p.name, p.stat().st_mtime_ns, p.stat().st_size)
                        for p in folder.iterdir() if p.suffix.lower() in EXTS))


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Add every photo in gallery/ to the SkySail Gallery page.")
    ap.add_argument("--html", default=str(here / "index.html"))
    ap.add_argument("--folder", default=str(here / "gallery"))
    ap.add_argument("--max-size", type=int, default=1400, help="longest side in pixels (default 1400)")
    ap.add_argument("--quality", type=int, default=80, help="WebP quality 1-100 (default 80)")
    ap.add_argument("--watch", action="store_true", help="keep running and rebuild when the folder changes")
    a = ap.parse_args()
    html, folder = Path(a.html), Path(a.folder)
    folder.mkdir(exist_ok=True)

    n = build(html, folder, a.max_size, a.quality)
    if n >= 0:
        print(f"Gallery built: {n} photos -> {html.name} ({html.stat().st_size/1e6:.1f} MB)")
    if not a.watch:
        return
    print(f"Watching {folder} ... drop photos in. Press Ctrl+C to stop.")
    last = signature(folder)
    try:
        while True:
            time.sleep(2)
            cur = signature(folder)
            if cur != last:
                time.sleep(1.5)                      # let a big copy finish
                cur = signature(folder)
                n = build(html, folder, a.max_size, a.quality)
                print(f"{time.strftime('%H:%M:%S')}  rebuilt: {n} photos")
                last = cur
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
